# Generated by Django 5.2 on 2025-04-29 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latirude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='panoramas/')),
                ('title', models.CharField(max_length=100)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.monument')),
            ],
        ),
        migrations.CreateModel(
            name='PanoramaPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotspot_yaw', models.FloatField()),
                ('hotspot_pitch', models.FloatField()),
                ('info', models.TextField()),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.panorama')),
                ('target_panorama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_points', to='main.panorama')),
            ],
        ),
    ]
