# Generated by Django 5.1.7 on 2025-04-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monument',
            name='latirude',
        ),
        migrations.AddField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
