# Generated by Django 5.1.7 on 2025-05-01 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_monument_latirude_monument_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(help_text='Вертикальный угол (-90 до 90)')),
                ('yaw', models.FloatField(help_text='Горизонтальный угол (-180 до 180)')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='main.panorama')),
                ('target_panorama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.panorama')),
            ],
        ),
    ]
