# Generated by Django 5.1.7 on 2025-05-01 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotspots/'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='haov',
            field=models.FloatField(default=360, verbose_name='Горизонтальный угол обзора'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='max_pitch',
            field=models.FloatField(default=27, verbose_name='Максимальный наклон'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='max_yaw',
            field=models.FloatField(default=130, verbose_name='Максимальный поворот'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='min_pitch',
            field=models.FloatField(default=-27, verbose_name='Минимальный наклон'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='min_yaw',
            field=models.FloatField(default=-130, verbose_name='Минимальный поворот'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='show_zoom_ctrl',
            field=models.BooleanField(default=True, verbose_name='Показывать зум'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='vaov',
            field=models.FloatField(default=55, verbose_name='Вертикальный угол обзора'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hotspots', to='main.panorama'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
