# Generated by Django 5.1.7 on 2025-05-01 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hotspot_image_panorama_haov_panorama_max_pitch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PanoramaPoint',
        ),
    ]
