# Generated by Django 5.1.7 on 2025-05-01 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_panoramapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='target_hfov',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)], verbose_name='Увеличение при переходе'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='transition_duration',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(5000)], verbose_name='Длительность перехода (мс)'),
        ),
    ]
