# Generated by Django 5.1.7 on 2025-05-01 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hotspot_target_hfov_hotspot_transition_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ['panorama', 'title'], 'verbose_name': 'Точка интереса', 'verbose_name_plural': 'Точки интереса'},
        ),
        migrations.AddField(
            model_name='hotspot',
            name='css_class',
            field=models.CharField(blank=True, default='custom-hotspot', max_length=50, verbose_name='CSS класс точки'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='entry_hotspot',
            field=models.ForeignKey(blank=True, help_text='Если нужно перейти к конкретной точке в целевой панораме', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hotspot', verbose_name='Точка входа в целевую панораму'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='target_pitch',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Наклон после перехода'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='target_yaw',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Поворот после перехода'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='main.panorama', verbose_name='Исходная панорама'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.FloatField(help_text='Вертикальный угол (-90 до 90)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hotspots', to='main.panorama', verbose_name='Целевая панорама'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.FloatField(help_text='Горизонтальный угол (-180 до 180)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
