# Generated by Django 5.1.7 on 2025-05-01 23:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_hotspot_options_hotspot_css_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={},
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='entry_hotspot',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='target_pitch',
        ),
        migrations.RemoveField(
            model_name='hotspot',
            name='target_yaw',
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='main.panorama'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.FloatField(help_text='Вертикальный угол (-90 до 90)'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_hfov',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hotspots', to='main.panorama'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='transition_duration',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.FloatField(help_text='Горизонтальный угол (-180 до 180)'),
        ),
    ]
