# Generated by Django 5.1.7 on 2025-05-01 23:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_hotspot_options_remove_hotspot_css_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_hfov',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.panorama'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='transition_duration',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='haov',
            field=models.FloatField(default=360),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='max_pitch',
            field=models.FloatField(default=27),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='max_yaw',
            field=models.FloatField(default=130),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='min_pitch',
            field=models.FloatField(default=-27),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='min_yaw',
            field=models.FloatField(default=-130),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='show_zoom_ctrl',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='vaov',
            field=models.FloatField(default=55),
        ),
    ]
