# Generated by Django 5.1.7 on 2025-05-02 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hotspot_pitch_alter_hotspot_target_hfov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='pitch',
            field=models.FloatField(help_text='Вертикальный угол (-90 до 90)'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_hfov',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)], verbose_name='Увеличение при переходе'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='target_panorama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hotspots', to='main.panorama'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='transition_duration',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(5000)], verbose_name='Длительность перехода (мс)'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='yaw',
            field=models.FloatField(help_text='Горизонтальный угол (-180 до 180)'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='haov',
            field=models.FloatField(default=360, verbose_name='Горизонтальный угол обзора'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='max_pitch',
            field=models.FloatField(default=27, verbose_name='Максимальный наклон'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='max_yaw',
            field=models.FloatField(default=130, verbose_name='Максимальный поворот'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='min_pitch',
            field=models.FloatField(default=-27, verbose_name='Минимальный наклон'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='min_yaw',
            field=models.FloatField(default=-130, verbose_name='Минимальный поворот'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='show_zoom_ctrl',
            field=models.BooleanField(default=True, verbose_name='Показывать зум'),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='vaov',
            field=models.FloatField(default=55, verbose_name='Вертикальный угол обзора'),
        ),
    ]
