# Generated by Django 5.1.7 on 2025-05-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_hotspot_options_hotspot_css_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Главная панорама'),
        ),
    ]
