# Generated by Django 5.1.7 on 2025-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_panorama_is_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='panorama',
            name='max_Hfov',
            field=models.FloatField(default=30, verbose_name='Максимальное увеличение'),
        ),
        migrations.AddField(
            model_name='panorama',
            name='min_Hfov',
            field=models.FloatField(default=30, verbose_name='Минимальное увеличение'),
        ),
    ]
